# Generated by Django 4.0.7 on 2022-09-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Остаток', 'verbose_name_plural': 'Остатьки'},
        ),
    ]
