# Generated by Django 4.1.1 on 2022-10-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
