# Generated by Django 4.1.1 on 2022-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_language_photo'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='stores', to='handbook.city'),
        ),
    ]
