# Generated by Django 4.0.7 on 2022-08-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
