# Generated by Django 4.1.1 on 2022-11-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productimage_product_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_id', models.IntegerField()),
                ('price_type_id', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='product.product')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
