# Generated by Django 4.1.1 on 2022-10-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productbase_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='city',
            new_name='cities',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='store',
            new_name='stores',
        ),
        migrations.AlterField(
            model_name='product',
            name='base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='product.productbase'),
        ),
    ]
