# Generated by Django 4.1.1 on 2022-11-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_language_photo'),
        ('product', '0004_alter_price_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price_type_id',
        ),
        migrations.RemoveField(
            model_name='price',
            name='quality_id',
        ),
        migrations.AddField(
            model_name='price',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='product.pricetype'),
        ),
        migrations.AddField(
            model_name='price',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='handbook.quality'),
        ),
    ]
