# Generated by Django 4.1.1 on 2022-11-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_language_photo'),
        ('store', '0002_alter_store_city'),
        ('product', '0005_remove_price_price_type_id_remove_price_quality_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpage',
            unique_together={('lang', 'store', 'city', 'product')},
        ),
    ]
