# Generated by Django 4.1.1 on 2022-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('handbook', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.AddField(
            model_name='category',
            name='stores',
            field=models.ManyToManyField(related_name='categories', to='store.store'),
        ),
    ]
