# Generated by Django 4.1.1 on 2022-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_remove_category_store_category_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='photo',
            field=models.ImageField(default='asd', upload_to='lang-images/'),
            preserve_default=False,
        ),
    ]
