# Generated by Django 4.1.1 on 2022-11-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_user', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='BusketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=10)),
                ('sales', models.CharField(blank=True, max_length=255, null=True)),
                ('new_price', models.IntegerField(blank=True, null=True)),
                ('busket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='busket.busket')),
            ],
            options={
                'verbose_name': 'Элементы корзины',
            },
        ),
    ]
