# Generated by Django 4.0.7 on 2022-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
