# Generated by Django 4.1.1 on 2022-10-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productbase_brand'),
        ('busket', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productbase'),
        ),
    ]
