# Generated by Django 4.1.1 on 2022-11-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beav', '0001_initial'),
        ('handbook', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='handbook.category'),
        ),
        migrations.AddField(
            model_name='entity',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='beav.group'),
        ),
        migrations.AddField(
            model_name='entity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='product.product'),
        ),
        migrations.AddField(
            model_name='entity',
            name='values',
            field=models.ManyToManyField(related_name='entities', to='beav.value'),
        ),
    ]
