# Generated by Django 4.1.1 on 2022-10-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('beav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='product.product'),
        ),
        migrations.AddField(
            model_name='entity',
            name='values',
            field=models.ManyToManyField(related_name='entities', to='beav.value'),
        ),
    ]
