# Generated by Django 4.1.1 on 2022-10-27 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_remove_category_store_category_stores'),
        ('beav', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='handbook.category'),
            preserve_default=False,
        ),
    ]
