# Generated by Django 4.1 on 2022-08-19 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresponse',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 11, 36, 15, 606015, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
