# Generated by Django 4.1 on 2022-08-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderresponse_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderresponse',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
