# Generated by Django 4.0.7 on 2022-09-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderresponse_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='operation_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
